# Cuadrados Mágicos

Un cuadrado mágico es un arreglo cuadrado de números dispuestos de forma tal que la suma de los números por columnas, renglones y diagonales principales sea la misma.
> **Ejemplo $3\times 3$:**
>
> Si $$Q_s=\begin{array}{|c|c|c|}\hline \alpha_1 & \alpha_2 & \alpha_3 \\  \hline \alpha_4 & \alpha_5 & \alpha_6 \\ \hline \alpha_7 & \alpha_8 & \alpha_9\\ \hline \end{array} $$ es un cuadrado mágico de súma mágica $s$: $$\begin{array}{cccc}&&& \begin{array}{|c|c|c|}\hline \alpha_1 & \alpha_2 & \alpha_3 \\  \hline \alpha_4 & \alpha_5 & \alpha_6 \\ \hline \alpha_7 & \alpha_8 & \alpha_9\\ \hline \end{array} & \begin{array}{c} \rightarrow s \\ \rightarrow s \\  \rightarrow s   \end{array}  \end{array} \\ \begin{array}{ccccccc} &\swarrow& \downarrow& \downarrow &\downarrow  &  \searrow &   \\ 
                       s     &  &         s&          s &         s  &       &    s \end{array} $$ entonces los números en el cuadrado mágico cumplen:
> 
>
>$\text{Suma de números por renglones: }
\begin{cases}
\alpha_1 +\alpha_2 +\alpha_3=s\\
\alpha_4 +\alpha_5 +\alpha_6=s\\
\alpha_7 +\alpha_8 +\alpha_9=s
\end{cases}$
>
>$\text{Suma de números por columnas: } 
\begin{cases}
\alpha_1 +\alpha_4 +\alpha_7=s\\
\alpha_2 +\alpha_5 +\alpha_8=s\\
\alpha_3 +\alpha_6 +\alpha_9=s\\\end{cases}$
>
>$\text{Suma de números por diagonales: }
\begin{cases}
\alpha_1 +\alpha_5 +\alpha_9=s\\
\alpha_3 +\alpha_5 +\alpha_7=s
\end{cases}$
>
> y tiene el siguiente sistema matricial asociado:
>
>$\begin{cases} 
\alpha_1 +\alpha_2 +\alpha_3=s& \\
\alpha_4 +\alpha_5 +\alpha_6=s& \\
\alpha_7 +\alpha_8 +\alpha_9=s& \\
\alpha_1 +\alpha_4 +\alpha_7=s& \\
\alpha_2 +\alpha_5 +\alpha_8=s& \\
\alpha_3 +\alpha_6 +\alpha_9=s& \\
\alpha_1 +\alpha_5 +\alpha_9=s& \\
\alpha_3 +\alpha_5 +\alpha_7=s& 
\end{cases}\Rightarrow \begin{cases}
\alpha_1 +\alpha_2 +\alpha_3-s=0& \\
\alpha_4 +\alpha_5 +\alpha_6-s=0& \\
\alpha_7 +\alpha_8 +\alpha_9-s=0& \\
\alpha_1 +\alpha_4 +\alpha_7-s=0\\
\alpha_2 +\alpha_5 +\alpha_8-s=0& \\
\alpha_3 +\alpha_6 +\alpha_9-s=0& \\
\alpha_1 +\alpha_5 +\alpha_9-s=0& \\
\alpha_3 +\alpha_5 +\alpha_7-s=0& 
\end{cases}$ 
>
>$\Rightarrow \left[ \begin{array}{cccccccccc}
1& 1& 1& 0& 0& 0& 0& 0& 0& -1\\
0& 0& 0& 1& 1& 1& 0& 0& 0& -1\\
0& 0& 0& 0& 0& 0& 1& 1& 1& -1\\
1& 0& 0& 1& 0& 0& 1& 0& 0& -1\\
0& 1& 0& 0& 1& 0& 0& 1& 0& -1\\ 
0& 0& 1& 0& 0& 1& 0& 0& 1& -1\\
1& 0& 0& 0& 1& 0& 0& 0& 1& -1\\
0& 0& 1& 0& 1& 0& 1& 0& 0& -1 \end{array} \right]_{8\times 10} \left[ \begin{array}{c} \alpha_1\\ \alpha_2\\ \alpha_3\\ \alpha_4\\ \alpha_5\\ \alpha_6\\ \alpha_7\\ \alpha_8\\ \alpha_9\\ s   \end{array} \right]_{10\times 1}=\left[ \begin{array}{c} 0\\ 0\\ 0\\ 0\\ 0\\ 0\\ 0\\ 0 \end{array} \right]_{8\times 1}$
>
> si $B=\left[\begin{array}{cccccccccc}
1& 1& 1& 0& 0& 0& 0& 0& 0& -1\\
0& 0& 0& 1& 1& 1& 0& 0& 0& -1\\
0& 0& 0& 0& 0& 0& 1& 1& 1& -1\\
1& 0& 0& 1& 0& 0& 1& 0& 0& -1\\
0& 1& 0& 0& 1& 0& 0& 1& 0& -1\\ 
0& 0& 1& 0& 0& 1& 0& 0& 1& -1\\
1& 0& 0& 0& 1& 0& 0& 0& 1& -1\\
0& 0& 1& 0& 1& 0& 1& 0& 0& -1 \end{array} \right]_{8\times 10}$ y $\alpha=\left[ \begin{array}{c} \alpha_1\\ \alpha_2\\ \alpha_3\\ \alpha_4\\ \alpha_5\\ \alpha_6\\ \alpha_7\\ \alpha_8\\ \alpha_9\\ s   \end{array} \right]_{10\times 1}$
>
> $$\Rightarrow \ \ B\alpha=0 $$

                   

Los elementos del cuadrado mágico $Q_s$ se encuentran en el vector $\alpha$, así que el problema de encontrar todos los cuadrados mágicos de suma $s$ se reduce a encontrar una base del núcleo de $B$.

Como hemos visto en clase este problema es fácil de resolver si podemos encontrar una matriz $A$ de columnas independientes, tal que en la matriz $C=AB$ sea fácil determinar la dependencia de sus columnas, aquí la matriz $A$ representa operaciones con los renglones de $B$.

Vamos a resolver este problema utilizando operaciones con renglones en el lenguaje de programación ``Julia``:

$$B=\left[\begin{array}{cccccccccc}
1& 1& 1& 0& 0& 0& 0& 0& 0& -1\\
0& 0& 0& 1& 1& 1& 0& 0& 0& -1\\
0& 0& 0& 0& 0& 0& 1& 1& 1& -1\\
1& 0& 0& 1& 0& 0& 1& 0& 0& -1\\
0& 1& 0& 0& 1& 0& 0& 1& 0& -1\\
0& 0& 1& 0& 0& 1& 0& 0& 1& -1\\
1& 0& 0& 0& 1& 0& 0& 0& 1& -1\\
0& 0& 1& 0& 1& 0& 1& 0& 0& -1 \end{array}\right]$$

Para ello crearemos dos funciones:
> `permuta` recibe una matriz $A$, pide dos índices $i,j$ y permuta los renglones $r_i^t$ y $r_j^t$
> $$A_{m\times n}=\begin{pmatrix}r_1^t\\ r_2^t\\ \vdots\\ r_i^t \\  \vdots\\ r_j^t \\  \vdots  \\ r_m^t \end{pmatrix},\ \ \ \ \ \ \ \text{permuta}_{ij}(A)=\begin{pmatrix}r_1^t\\ r_2^t\\ \vdots\\ r_j^t \\  \vdots\\ r_i^t \\  \vdots  \\ r_m^t \end{pmatrix}$$

> `renglones` recibe una matriz $A$, pide dos índices $j,i$ y escalares $\lambda_j, \lambda_i$ e intercambia el renglón   $r_j^t$ por el renglón $\lambda_ir_i^t+\lambda_jr_j^t$
> $$A_{m\times n}=\begin{pmatrix}r_1^t\\ r_2^t\\ \vdots\\ r_i^t \\  \vdots\\ r_j^t \\  \vdots  \\ r_m^t \end{pmatrix},\ \ \ \ \ \ \ \text{renglones}_{ij}(A)=\begin{pmatrix}r_1^t\\ r_2^t\\ \vdots\\ r_i^t \\  \vdots\\ \lambda_ir_i^t+\lambda_jr_j^t \\  \vdots  \\ r_m^t \end{pmatrix}$$

In [1]:
# Función permuta
# Esta función toma una matriz A y dos enteros i,j
# Regresa la matriz en la que se han permutado los renglones i y j

function permuta(A,i,j)
    Aₚ=copy(A)
    # Aquí se intercambian los renglones
    ri=copy(Aₚ[i,:])
    Aₚ[i,:]=Aₚ[j,:]
    Aₚ[j,:]=ri
    return Aₚ
end    

permuta (generic function with 1 method)

In [2]:
# Función opera
# Esta función toma una matriz A, dos renglones rᵢ y rⱼ y dos escalares λᵢ y λⱼ
# sustituye el primero renglon por el renglon λᵢ*rᵢ+λⱼ*rⱼ

function renglones(A,i,λᵢ,j,λⱼ)
    Aₒ=copy(A)
    # Aquí se hacen las operaciones con renglones
    rᵢ=copy(Aₒ[i,:])
    rⱼ=copy(Aₒ[j,:])
    Aₒ[j,:]=λᵢ*rᵢ+λⱼ*rⱼ
    return Aₒ
end 

renglones (generic function with 1 method)

In [3]:
# Función ver
# Esta función toma una matriz A y la muestra al usuario con distintos mensajes

function ver(A)
    (m,n)=size(A)
    println("La matriz actual es:")
        for r in 1:m
            println(A[r,:]')
        end   
end 

function ver_resultante(A)
    (m,n)=size(A)
    println("La matriz resultante es:")
        for r in 1:m
            println(A[r,:]')
        end   
end

function ver_permutada(A)
    (m,n)=size(A)
    println("La matriz permutada es:")
        for r in 1:m
            println(A[r,:]')
        end   
end

ver_permutada (generic function with 1 method)

In [4]:
# Esta función interactua con el usuario para aplicar después la función permuta
function operacion_permuta(A)
    Aₚ=copy(A)
        println("Introduzca el índice del primer renglón a permutar")
                i=readline()
        println("Introduzca el índice del segundo renglón a permutar")
                j=readline()
            i=parse(Int64, i)
            j=parse(Int64, j)
        B=permuta(Aₚ,i,j)
        # Aquí mostramos la matriz permutada 
        ver_permutada(B)
        # Aquí preguntamos si el cambio realizado se quiere guardar
        println("¿Desea guardar cambios? (y/n)")
        testp=readline()
        if (xor(testp=="y" , testp=="Y"))
            Aₚ=B
        end
    return Aₚ
end 

operacion_permuta (generic function with 1 method)

In [5]:
# Esta función interactua con el usuario para aplicar después la función renglones
function operacion_renglones(A)
        Aᵣ=copy(A)
            println("Introduzca el índice del renglón que contiene al pivote")
                i=readline()
            println("Introduzca el coeficiente entero que multiplica a este renglón")
                λᵢ=readline()
            println("Introduzca el índice del renglón a sustituir")
                j=readline()
            println("Introduzca el coeficiente entero que multiplica a este renglón")
                λⱼ=readline()
            
            i=parse(Int64, i)
            j=parse(Int64, j)
            λᵢ=parse(Int64, λᵢ)
            λⱼ=parse(Int64, λⱼ) 
    
        B=renglones(A,i,λᵢ,j,λⱼ)
        
        # Aquí mostramos la matriz resultante 
        ver_resultante(B)
       
        # Aquí preguntamos si el cambio realizado se quiere guardar
        println("¿Desea guardar cambios? (y/n)")
        testp=readline()
        if (xor(testp=="y" , testp=="Y"))
            Aᵣ=B
        end
    return Aᵣ
end 

operacion_renglones (generic function with 1 method)

In [6]:
# Esta función interactua con el usuario para facilitar la aplicación sucesiva de las operaciones entre renglones
function opera(A)
    test0="1"
    while(xor(test0=="1" , test0=="2"))
        ver(A)
        println("¿Qué tipo de operación desea realizar?")
        println("1.-Permutación")
        println("2.-Operaciones con renglones")
        println("3.-Salir")
    
        test0=readline()
    
        if (test0=="1")
            A=operacion_permuta(A)
        end 
    
        if (test0=="2")
            A=operacion_renglones(A)
        end 
    end

    return A

end

opera (generic function with 1 method)

# Ejemplo 1
Definimos la matriz $$B=\left[\begin{array}{cccccccccc}
1& 1& 1& 0& 0& 0& 0& 0& 0& -1\\
0& 0& 0& 1& 1& 1& 0& 0& 0& -1\\
0& 0& 0& 0& 0& 0& 1& 1& 1& -1\\
1& 0& 0& 1& 0& 0& 1& 0& 0& -1\\
0& 1& 0& 0& 1& 0& 0& 1& 0& -1\\
0& 0& 1& 0& 0& 1& 0& 0& 1& -1\\
1& 0& 0& 0& 1& 0& 0& 0& 1& -1\\
0& 0& 1& 0& 1& 0& 1& 0& 0& -1 \end{array}\right]$$

In [7]:
B=[1 1 1 0 0 0 0 0 0 -1;
   0 0 0 1 1 1 0 0 0 -1;
   0 0 0 0 0 0 1 1 1 -1;
   1 0 0 1 0 0 1 0 0 -1;
   0 1 0 0 1 0 0 1 0 -1; 
   0 0 1 0 0 1 0 0 1 -1;    
   1 0 0 0 1 0 0 0 1 -1;
   0 0 1 0 1 0 1 0 0 -1]

8×10 Array{Int64,2}:
 1  1  1  0  0  0  0  0  0  -1
 0  0  0  1  1  1  0  0  0  -1
 0  0  0  0  0  0  1  1  1  -1
 1  0  0  1  0  0  1  0  0  -1
 0  1  0  0  1  0  0  1  0  -1
 0  0  1  0  0  1  0  0  1  -1
 1  0  0  0  1  0  0  0  1  -1
 0  0  1  0  1  0  1  0  0  -1

Como el elemento en (1,1) es distinto de cero, hacemos ceros debajo con el primer renglón:
* restamos el primer renglón al cuarto: $$r^t_4\leftarrow r^t_4-r^t_1$$
* restamos el primer renglón al septimo: $$r^t_7\leftarrow r^t_7-r^t_1$$
$$B=\left[\begin{array}{c|ccccccccc}
 1&  1&  1&  0&  0&  0&  0&  0&  0&  -1\\\hline
 0&  0&  0&  1&  1&  1&  0&  0&  0&  -1\\
 0&  0&  0&  0&  0&  0&  1&  1&  1&  -1\\
 1&  0&  0&  1&  0&  0&  1&  0&  0&  -1\\
 0&  1&  0&  0&  1&  0&  0&  1&  0&  -1\\
 0&  0&  1&  0&  0&  1&  0&  0&  1&  -1\\
 1&  0&  0&  0&  1&  0&  0&  0&  1&  -1\\
 0&  0&  1&  0&  1&  0&  1&  0&  0&  -1\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\\
r_4^t-r^t_1\\
r_5^t\\
r_6^t\\
r_7^t-r^t_1\\
r_8^t \end{array}\right] $$

In [8]:
C=opera(B)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[1 0 0 1 0 0 1 0 0 -1]
[0 1 0 0 1 0 0 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[1 0 0 0 1 0 0 0 1 -1]
[0 0 1 0 1 0 1 0 0 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 1
Introduzca el coeficiente entero que multiplica a este renglón
stdin> -1
Introduzca el índice del renglón a sustituir
stdin> 4
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 1 0 0 1 0 0 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[1 0 0 0 1 0 0 0 1 -1]
[0 0 1 0 1 0 1 0 0 -1]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 1 0 0 1 0 0 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[1 0 0 0 1 0 0 0 1 -1

8×10 Array{Int64,2}:
 1   1   1  0  0  0  0  0  0  -1
 0   0   0  1  1  1  0  0  0  -1
 0   0   0  0  0  0  1  1  1  -1
 0  -1  -1  1  0  0  1  0  0   0
 0   1   0  0  1  0  0  1  0  -1
 0   0   1  0  0  1  0  0  1  -1
 0  -1  -1  0  1  0  0  0  1   0
 0   0   1  0  1  0  1  0  0  -1

In [9]:
C

8×10 Array{Int64,2}:
 1   1   1  0  0  0  0  0  0  -1
 0   0   0  1  1  1  0  0  0  -1
 0   0   0  0  0  0  1  1  1  -1
 0  -1  -1  1  0  0  1  0  0   0
 0   1   0  0  1  0  0  1  0  -1
 0   0   1  0  0  1  0  0  1  -1
 0  -1  -1  0  1  0  0  0  1   0
 0   0   1  0  1  0  1  0  0  -1

Como el elemento en (2,2) es nulo hacemos una permutación:
* intercambiamos el segundo renglón y el cuarto  $$r^t_2\leftrightarrow r^t_4$$
$$B\rightarrow\left[\begin{array}{cc|cccccccc}
 1&  1&  1&   0&   0&  0&   0&  0&   0&  -1\\
 0&  0&  0&   1&   1&  1&   0&  0&   0&  -1\\\hline
 0&  0&  0&   0&   0&  0&   1&  1&   1&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&  0&   0&   0\\
 0&  1&  0&   0&   1&  0&   0&  1&   0&  -1\\
 0&  0&  1&   0&   0&  1&   0&  0&   1&  -1\\
 0&  -1&  -1&   0&  1&  0&   0&  0&  1&   0\\
 0&  0&  1&   0&   1&  0&   1&  0&   0&  -1\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\leftarrow r_4^t\\
r_3^t\\
r_4^t\leftarrow r^t_2\\
r_5^t\\
r_6^t\\
r_7^t\\
r_8^t \end{array}\right] $$

In [10]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 1 0 0 1 0 0 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 -1 -1 0 1 0 0 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 1
Introduzca el índice del primer renglón a permutar
stdin> 2
Introduzca el índice del segundo renglón a permutar
stdin> 4
La matriz permutada es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 1 0 0 1 0 0 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 -1 -1 0 1 0 0 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 1 0 0 1 0 0 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 -1 -1 0 1 0 0 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 3


8×10 Array{Int64,2}:
 1   1   1  0  0  0  0  0  0  -1
 0  -1  -1  1  0  0  1  0  0   0
 0   0   0  0  0  0  1  1  1  -1
 0   0   0  1  1  1  0  0  0  -1
 0   1   0  0  1  0  0  1  0  -1
 0   0   1  0  0  1  0  0  1  -1
 0  -1  -1  0  1  0  0  0  1   0
 0   0   1  0  1  0  1  0  0  -1

Ahora que el elemento en (2,2) es distinto de cero, hacemos ceros debajo con el segundo renglón:
* sumamos el segundo renglón al quinto: $$r^t_5\leftarrow r^t_5+r^t_2$$
* restamos el segundo renglón al séptimo: $$r^t_7\leftarrow r^t_7-r^t_2$$
$$B\rightarrow\left[\begin{array}{cc|cccccccc}
 1&  1&  1&   0&   0&  0&   0&  0&   0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&  0&   0&   0\\ \hline
 0&  0&  0&   0&   0&  0&   1&  1&   1&  -1\\
 0&  0&  0&   1&   1&  1&   0&  0&   0&  -1\\
 0&  1&  0&   0&   1&  0&   0&  1&   0&  -1\\
 0&  0&  1&   0&   0&  1&   0&  0&   1&  -1\\
 0&  -1&  -1&   0&  1&  0&   0&  0&  1&   0\\
 0&  0&  1&   0&   1&  0&   1&  0&   0&  -1\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\\
r_4^t\\
r_5^t+r^t_2\\
r_6^t\\
r_7^t-r^t_2\\
r_8^t \end{array}\right] $$

In [11]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 1 0 0 1 0 0 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 -1 -1 0 1 0 0 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 2
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
Introduzca el índice del renglón a sustituir
stdin> 5
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 -1 -1 0 1 0 0 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 -1 -1 0 1 0 0 

8×10 Array{Int64,2}:
 1   1   1   0  0  0   0  0  0  -1
 0  -1  -1   1  0  0   1  0  0   0
 0   0   0   0  0  0   1  1  1  -1
 0   0   0   1  1  1   0  0  0  -1
 0   0  -1   1  1  0   1  1  0  -1
 0   0   1   0  0  1   0  0  1  -1
 0   0   0  -1  1  0  -1  0  1   0
 0   0   1   0  1  0   1  0  0  -1

Como el elemento en (3,3) es nulo hacemos una permutación:
* intercambiamos el tercer renglón y el quinto  $$r^t_3\leftrightarrow r^t_5$$
$$B\rightarrow\left[\begin{array}{ccc|ccccccc}
 1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  0&   0&   0&  0&   1&   1&  1&  -1\\\hline
 0&  0&  0&   1&   1&  1&   0&   0&  0&  -1\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\
 0&  0&  1&   0&   0&  1&   0&   0&  1&  -1\\
 0&  0&  0&  -1&   1&  0&  -1&   0&  1&   0\\
 0&  0&  1&   0&   1&  0&   1&   0&  0&  -1\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\leftarrow r_5^t\\
r_4^t\\
r_5^t\leftarrow r^t_3\\
r_6^t\\
r_7^t\\
r_8^t \end{array}\right] $$

In [12]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 0 0 -1 1 0 -1 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 1
Introduzca el índice del primer renglón a permutar
stdin> 3
Introduzca el índice del segundo renglón a permutar
stdin> 5
La matriz permutada es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 0 0 -1 1 0 -1 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 0 0 -1 1 0 -1 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 3


8×10 Array{Int64,2}:
 1   1   1   0  0  0   0  0  0  -1
 0  -1  -1   1  0  0   1  0  0   0
 0   0  -1   1  1  0   1  1  0  -1
 0   0   0   1  1  1   0  0  0  -1
 0   0   0   0  0  0   1  1  1  -1
 0   0   1   0  0  1   0  0  1  -1
 0   0   0  -1  1  0  -1  0  1   0
 0   0   1   0  1  0   1  0  0  -1

Ahora que el elemento en (3,3) es distinto de cero, hacemos ceros debajo con el tercer renglón:
* sumanos el tercer renglón al sexto: $$r^t_6\leftarrow r^t_6+r^t_3$$
* sumanos el tercer renglón al octavo: $$r^t_8\leftarrow r^t_8+r^t_3$$
$$B\rightarrow\left[\begin{array}{ccc|ccccccc}
 1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\\hline
 0&  0&  0&   1&   1&  1&   0&   0&  0&  -1\\
 0&  0&  0&   0&   0&  0&   1&   1&  1&  -1\\
 0&  0&  1&   0&   0&  1&   0&   0&  1&  -1\\
 0&  0&  0&  -1&   1&  0&  -1&   0&  1&   0\\
 0&  0&  1&   0&   1&  0&   1&   0&  0&  -1\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\\
r_4^t\\
r_5^t\\
r_6^t+r^t_3\\
r_7^t\\
r_8^t+r^t_3 \end{array}\right] $$

In [12]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 1 0 0 1 0 0 1 -1]
[0 0 0 -1 1 0 -1 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 3
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
Introduzca el índice del renglón a sustituir
stdin> 6
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 1 1 1 -2]
[0 0 0 -1 1 0 -1 0 1 0]
[0 0 1 0 1 0 1 0 0 -1]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 1 1 1 -2]
[0 0 0 -1 1 0 -1

8×10 Array{Int64,2}:
 1   1   1   0  0  0   0  0  0  -1
 0  -1  -1   1  0  0   1  0  0   0
 0   0  -1   1  1  0   1  1  0  -1
 0   0   0   1  1  1   0  0  0  -1
 0   0   0   0  0  0   1  1  1  -1
 0   0   0   1  1  1   1  1  1  -2
 0   0   0  -1  1  0  -1  0  1   0
 0   0   0   1  2  0   2  1  0  -2

Como que el elemento en (4,4) es distinto de cero, hacemos ceros debajo con el cuarto renglón:
* restamos el cuarto renglón al sexto: $$r^t_6\leftarrow r^t_6-r^t_4$$
* sumamos el cuarto renglón al séptimo: $$r^t_7\leftarrow r^t_7+r^t_4$$
* restamos el cuarto renglón al octavo: $$r^t_8\leftarrow r^t_8-r^t_4$$

$$B\rightarrow\left[\begin{array}{cccc|cccccc}
1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\
 0&  0&  0&   1&   1&   1&   0&   0&   0&  -1\\ \hline
 0&  0&  0&   0&   0&   0&   1&   1&   1&  -1\\
 0&  0&  0&   1&   1&   1&   1&   1&   1&   -2\\
 0&  0&  0&  -1&   1&   0&  -1&   0&   1&   0\\
 0&  0&  0&   1&   2&   0&   2&   1&   0&   -2\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\\
r_4^t\\
r_5^t\\
r_6^t-r^t_4\\
r_7^t+r^t_4\\
r_8^t-r^t_4 \end{array}\right] $$

In [13]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 1 1 1 1 1 1 -2]
[0 0 0 -1 1 0 -1 0 1 0]
[0 0 0 1 2 0 2 1 0 -2]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 4
Introduzca el coeficiente entero que multiplica a este renglón
stdin> -1
Introduzca el índice del renglón a sustituir
stdin> 6
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 -1 1 0 -1 0 1 0]
[0 0 0 1 2 0 2 1 0 -2]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 -1 1 0 -

8×10 Array{Int64,2}:
 1   1   1  0  0   0   0  0  0  -1
 0  -1  -1  1  0   0   1  0  0   0
 0   0  -1  1  1   0   1  1  0  -1
 0   0   0  1  1   1   0  0  0  -1
 0   0   0  0  0   0   1  1  1  -1
 0   0   0  0  0   0   1  1  1  -1
 0   0   0  0  2   1  -1  0  1  -1
 0   0   0  0  1  -1   2  1  0  -1

Como el elemento en (5,5) es nulo hacemos una permutación:
* intercambiamos el quinto renglón y el octavo  $$r^t_5\leftrightarrow r^t_8$$
$$B\rightarrow\left[\begin{array}{ccccc|ccccc}
 1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\
 0&  0&  0&   1&   1&  1&   0&   0&   0&  -1\\
 0&  0&  0&   0&   0&  0&   1&   1&   1&  -1\\\hline
 0&  0&  0&   0&   0&  0&   1&   1&   1&  -1\\
 0&  0&  0&   0&   2&  1&  -1&   0&   1&  -1\\
 0&  0&  0&   0&   1& -1&   2&   1&   0&  -1\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\\
r_4^t\\
r_5^t\leftarrow r^t_8\\
r_6^t\\
r_7^t\\
r_8^t\leftarrow r_5^t \end{array}\right] $$

In [15]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 2 1 -1 0 1 -1]
[0 0 0 0 1 -1 2 1 0 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 1
Introduzca el índice del primer renglón a permutar
stdin> 5
Introduzca el índice del segundo renglón a permutar
stdin> 8
La matriz permutada es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 2 1 -1 0 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 2 1 -1 0 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 3


8×10 Array{Int64,2}:
 1   1   1  0  0   0   0  0  0  -1
 0  -1  -1  1  0   0   1  0  0   0
 0   0  -1  1  1   0   1  1  0  -1
 0   0   0  1  1   1   0  0  0  -1
 0   0   0  0  1  -1   2  1  0  -1
 0   0   0  0  0   0   1  1  1  -1
 0   0   0  0  2   1  -1  0  1  -1
 0   0   0  0  0   0   1  1  1  -1

Como que el elemento en (5,5) es distinto de cero, hacemos ceros debajo con el quinto renglón:
* restamos el doble del quinto renglón al séptimo: $$r^t_7\leftarrow r^t_7-2r^t_5$$


$$B\rightarrow\left[\begin{array}{ccccc|ccccc}
 1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\
 0&  0&  0&   1&   1&  1&   0&   0&   0&  -1\\
 0&  0&  0&   0&   1& -1&   2&   1&   0&  -1\\ \hline
 0&  0&  0&   0&   0&  0&   1&   1&   1&  -1\\
 0&  0&  0&   0&   2&  1&  -1&   0&   1&  -1\\
  0&  0&  0&   0&   0&  0&   1&   1&   1&  -1
\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\\
r_4^t\\
r_5^t\\
r_6^t\\
r_7^t\leftarrow r^t_7-2r^t_5\\
r_8^t \end{array}\right] $$

In [16]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 2 1 -1 0 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 5
Introduzca el coeficiente entero que multiplica a este renglón
stdin> -2
Introduzca el índice del renglón a sustituir
stdin> 7
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 3 -5 -2 1 1]
[0 0 0 0 0 0 1 1 1 -1]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 3

8×10 Array{Int64,2}:
 1   1   1  0  0   0   0   0  0  -1
 0  -1  -1  1  0   0   1   0  0   0
 0   0  -1  1  1   0   1   1  0  -1
 0   0   0  1  1   1   0   0  0  -1
 0   0   0  0  1  -1   2   1  0  -1
 0   0   0  0  0   0   1   1  1  -1
 0   0   0  0  0   3  -5  -2  1   1
 0   0   0  0  0   0   1   1  1  -1

Como el elemento en (6,6) es nulo hacemos una permutación:
* intercambiamos el sexto renglón y el séptimo  $$r^t_6\leftrightarrow r^t_7$$
$$B\rightarrow\left[\begin{array}{cccccc|cccc}
 1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\
 0&  0&  0&   1&   1&  1&   0&   0&   0&  -1\\
 0&  0&  0&   0&   1& -1&   2&   1&   0&  -1\\ 
 0&  0&  0&   0&   0&  0&   1&   1&   1&  -1\\\hline
 0&  0&  0&   0&   0&  3&  -5&   -2&   1&  1\\
  0&  0&  0&   0&   0&  0&   1&   1&   1&  -1\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\\
r_4^t\\
r_5^t\\
r_6^t\leftarrow r^t_7\\
r_7^t\leftarrow r_6^t \\
r_8^t \end{array}\right] $$

In [17]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 3 -5 -2 1 1]
[0 0 0 0 0 0 1 1 1 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 1
Introduzca el índice del primer renglón a permutar
stdin> 6
Introduzca el índice del segundo renglón a permutar
stdin> 7
La matriz permutada es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 3 -5 -2 1 1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 3 -5 -2 1 1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 3


8×10 Array{Int64,2}:
 1   1   1  0  0   0   0   0  0  -1
 0  -1  -1  1  0   0   1   0  0   0
 0   0  -1  1  1   0   1   1  0  -1
 0   0   0  1  1   1   0   0  0  -1
 0   0   0  0  1  -1   2   1  0  -1
 0   0   0  0  0   3  -5  -2  1   1
 0   0   0  0  0   0   1   1  1  -1
 0   0   0  0  0   0   1   1  1  -1

Como ya hay ceros debajo del elemento en (6,6) no hacemos nada en este paso


Como que el elemento en (7,7) es distinto de cero, hacemos ceros debajo con el séptimo renglón:
* restamos el séptimo renglón al octavo: $$r^t_8\leftarrow r^t_8-r^t_7$$

$$B\rightarrow\left[\begin{array}{cccccc|cccc}
1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\
 0&  0&  0&   1&   1&  1&   0&   0&   0&  -1\\
 0&  0&  0&   0&   1& -1&   2&   1&   0&  -1\\ 
  0&  0&  0&   0&   0&  3&  -5&   -2&   1&  1\\
 0&  0&  0&   0&   0&  0&   1&   1&   1&  -1\\\hline
  0&  0&  0&   0&   0&  0&   1&   1&   1&  -1
\end{array}\right]\rightarrow
\left[\begin{array}{c}
r_1^t\\
r_2^t\\
r_3^t\\
r_4^t\\
r_5^t\\
r_6^t\\
r_7^t\\
r_8^t\leftarrow r^t_8-r^t_7 \end{array}\right] $$




In [18]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 3 -5 -2 1 1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 1 1 1 -1]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 7
Introduzca el coeficiente entero que multiplica a este renglón
stdin> -1
Introduzca el índice del renglón a sustituir
stdin> 8
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 3 -5 -2 1 1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 3 -5 -2 1 1]
[0 0 0 0 0 0

8×10 Array{Int64,2}:
 1   1   1  0  0   0   0   0  0  -1
 0  -1  -1  1  0   0   1   0  0   0
 0   0  -1  1  1   0   1   1  0  -1
 0   0   0  1  1   1   0   0  0  -1
 0   0   0  0  1  -1   2   1  0  -1
 0   0   0  0  0   3  -5  -2  1   1
 0   0   0  0  0   0   1   1  1  -1
 0   0   0  0  0   0   0   0  0   0

En la matriz obtenida, es fácil notar que la últimas tres columnas son linealmente dependientes de las primeras siete:
$$B\rightarrow\left[\begin{array}{ccccccc|ccc}
1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\
 0&  0&  0&   1&   1&  1&   0&   0&   0&  -1\\
 0&  0&  0&   0&   1& -1&   2&   1&   0&  -1\\ 
  0&  0&  0&   0&   0&  3&  -5&   -2&   1&  1\\
 0&  0&  0&   0&   0&  0&   1&   1&   1&  -1\\\hline
  0&  0&  0&   0&   0&  0&   0&   0&   0&  0
\end{array}\right]$$

>**Idea**:
>
>Para encontrar esta dependencia de forma explícita aún debemos de resolver el sistema triangular para cada una de las columnas de la derecha, esto se puede hacer de diferentes maneras, una de ellas es volver al esquema algebraico e ir resolviendo por sustitución, pero de manera equivalente y en el mismo esquema lo que vamos a hacer aquí es hacer ceros sobre los pivotes que encontramos en cada columna independiente: 

Para hacer ceros sobre el pivote en (7,7):
* sumamos el séptimo renglón multiplicado por 5 al sexto: $$r^t_6\leftarrow r^t_6+5r^t_7$$
* restamos el séptimo renglón multiplicado por 2 al quinto: $$r^t_5\leftarrow r^t_5-2r^t_7$$
* restamos el séptimo renglón multiplicado por 1 al tercero: $$r^t_3\leftarrow r^t_3-r^t_7$$
* restamos el séptimo renglón multiplicado por 1 al segundo: $$r^t_2\leftarrow r^t_2-r^t_7$$

$$B\rightarrow\left[\begin{array}{cccccc|c|ccc}
1&  1&  1&   0&   0&  0&   0&   0&  0&  -1\\
 0&  -1&  -1&  1&   0&  0&  1&   0&  0&   0\\
 0&  0&  -1&  1&  1&  0&  1&  1&  0&   -1\\
 0&  0&  0&   1&   1&  1&   0&   0&   0&  -1\\
 0&  0&  0&   0&   1& -1&   2&   1&   0&  -1\\ 
  0&  0&  0&   0&   0&  3&  -5&   -2&   1&  1\\
 0&  0&  0&   0&   0&  0&   1&   1&   1&  -1\\\hline
  0&  0&  0&   0&   0&  0&   0&   0&   0&  0
\end{array}\right]$$

In [19]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 3 -5 -2 1 1]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 7
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 5
Introduzca el índice del renglón a sustituir
stdin> 6
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 1 0 0 0]
[0 0 -1 1 1 0 1 1 0 -1]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 2 1 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1

8×10 Array{Int64,2}:
 1   1   1  0  0   0  0   0   0  -1
 0  -1  -1  1  0   0  0  -1  -1   1
 0   0  -1  1  1   0  0   0  -1   0
 0   0   0  1  1   1  0   0   0  -1
 0   0   0  0  1  -1  0  -1  -2   1
 0   0   0  0  0   3  0   3   6  -4
 0   0   0  0  0   0  1   1   1  -1
 0   0   0  0  0   0  0   0   0   0

Para hacer ceros sobre el pivote en (6,6):
* sumamos el sexto renglón al triple del quinto: $$r^t_5\leftarrow 3r^t_5+r^t_6$$
* restamos el sexto renglón al triple del cuarto: $$r^t_4\leftarrow 3r^t_4-r^t_6$$

$$B\rightarrow\left[\begin{array}{ccccc|c|c|ccc}
 1&   1&   1&  0&  0&   0&  0&   0&   0&  -1\\
 0&  -1&  -1&  1&  0&   0&  0&  -1&  -1&   1\\
 0&   0&  -1&  1&  1&   0&  0&   0&  -1&   0\\
 0&   0&   0&  1&  1&   1&  0&   0&   0&  -1\\
 0&   0&   0&  0&  1&  -1&  0&  -1&  -2&   1\\
 0&   0&   0&  0&  0&   3&  0&   3&   6&  -4\\
 0&   0&   0&  0&  0&   0&  1&   1&   1&  -1\\ \hline
 0&   0&   0&  0&  0&   0&  0&   0&   0&   0
\end{array}\right]$$

In [21]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -1 1 1 0 0 0 -1 0]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 1 -1 0 -1 -2 1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 6
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
Introduzca el índice del renglón a sustituir
stdin> 5
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 3
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -1 1 1 0 0 0 -1 0]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -1 1 1 0 0 0 -1 0]
[0 0 0 1 1 1 0 0 0 -1]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0

8×10 Array{Int64,2}:
 1   1   1  0  0  0  0   0   0  -1
 0  -1  -1  1  0  0  0  -1  -1   1
 0   0  -1  1  1  0  0   0  -1   0
 0   0   0  3  3  0  0  -3  -6   1
 0   0   0  0  3  0  0   0   0  -1
 0   0   0  0  0  3  0   3   6  -4
 0   0   0  0  0  0  1   1   1  -1
 0   0   0  0  0  0  0   0   0   0

Para hacer ceros sobre el pivote en (5,5):
* restamos el quinto renglón al cuarto: $$r^t_4\leftarrow r^t_4-r^t_5$$
* restamos el quinto renglón al triple del tercero: $$r^t_3\leftarrow 3r^t_3-r^t_5$$

$$B\rightarrow\left[\begin{array}{cccc|c|cc|ccc}
 1&   1&   1&  0&  0&  0&  0&   0&   0&  -1\\
 0&  -1&  -1&  1&  0&  0&  0&  -1&  -1&   1\\
 0&   0&  -1&  1&  1&  0&  0&   0&  -1&   0\\
 0&   0&   0&  3&  3&  0&  0&  -3&  -6&   1\\
 0&   0&   0&  0&  3&  0&  0&   0&   0&  -1\\
 0&   0&   0&  0&  0&  3&  0&   3&   6&  -4\\
 0&   0&   0&  0&  0&  0&  1&   1&   1&  -1\\ \hline
 0&   0&   0&  0&  0&  0&  0&   0&   0&   0
\end{array}\right]$$

In [23]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -1 1 1 0 0 0 -1 0]
[0 0 0 3 3 0 0 -3 -6 1]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 5
Introduzca el coeficiente entero que multiplica a este renglón
stdin> -1
Introduzca el índice del renglón a sustituir
stdin> 4
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -1 1 1 0 0 0 -1 0]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -1 1 1 0 0 0 -1 0]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0

8×10 Array{Int64,2}:
 1   1   1  0  0  0  0   0   0  -1
 0  -1  -1  1  0  0  0  -1  -1   1
 0   0  -3  3  0  0  0   0  -3   1
 0   0   0  3  0  0  0  -3  -6   2
 0   0   0  0  3  0  0   0   0  -1
 0   0   0  0  0  3  0   3   6  -4
 0   0   0  0  0  0  1   1   1  -1
 0   0   0  0  0  0  0   0   0   0

Para hacer ceros sobre el pivote en (4,4):
* restamos el cuarto renglón al tercero: $$r^t_3\leftarrow r^t_3-r^t_4$$
* restamos el cuarto renglón al triple del segundo: $$r^t_2\leftarrow 3r^t_2-r^t_4$$

$$B\rightarrow\left[\begin{array}{ccc|c|ccc|ccc}
 1&   1&   1&  0&  0&  0&  0&   0&   0&  -1\\
 0&  -1&  -1&  1&  0&  0&  0&  -1&  -1&   1\\
 0&   0&  -3&  3&  0&  0&  0&   0&  -3&   1\\
 0&   0&   0&  3&  0&  0&  0&  -3&  -6&   2\\
 0&   0&   0&  0&  3&  0&  0&   0&   0&  -1\\
 0&   0&   0&  0&  0&  3&  0&   3&   6&  -4\\
 0&   0&   0&  0&  0&  0&  1&   1&   1&  -1\\ \hline
 0&   0&   0&  0&  0&  0&  0&   0&   0&   0
\end{array}\right]$$

In [24]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -3 3 0 0 0 0 -3 1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 4
Introduzca el coeficiente entero que multiplica a este renglón
stdin> -1
Introduzca el índice del renglón a sustituir
stdin> 3
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -3 0 0 0 0 3 3 -1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -1 -1 1 0 0 0 -1 -1 1]
[0 0 -3 0 0 0 0 3 3 -1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0

8×10 Array{Int64,2}:
 1   1   1  0  0  0  0   0   0  -1
 0  -3  -3  0  0  0  0   0   3   1
 0   0  -3  0  0  0  0   3   3  -1
 0   0   0  3  0  0  0  -3  -6   2
 0   0   0  0  3  0  0   0   0  -1
 0   0   0  0  0  3  0   3   6  -4
 0   0   0  0  0  0  1   1   1  -1
 0   0   0  0  0  0  0   0   0   0

Para hacer ceros sobre el pivote en (3,3):
* restamos el tercer renglón al segundo: $$r^t_2\leftarrow r^t_2-r^t_3$$
* sumamos el tercer renglón al triple del primero: $$r^t_1\leftarrow 3r^t_1+r^t_3$$

$$B\rightarrow\left[\begin{array}{cc|c|cccc|ccc}
 1&   1&   1&  0&  0&  0&  0&   0&   0&  -1\\
 0&  -3&  -3&  0&  0&  0&  0&   0&   3&   1\\
 0&   0&  -3&  0&  0&  0&  0&   3&   3&  -1\\
 0&   0&   0&  3&  0&  0&  0&  -3&  -6&   2\\
 0&   0&   0&  0&  3&  0&  0&   0&   0&  -1\\
 0&   0&   0&  0&  0&  3&  0&   3&   6&  -4\\
 0&   0&   0&  0&  0&  0&  1&   1&   1&  -1\\ \hline
 0&   0&   0&  0&  0&  0&  0&   0&   0&   0
\end{array}\right]$$

In [25]:
C=opera(C)

La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -3 -3 0 0 0 0 0 3 1]
[0 0 -3 0 0 0 0 3 3 -1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 3
Introduzca el coeficiente entero que multiplica a este renglón
stdin> -1
Introduzca el índice del renglón a sustituir
stdin> 2
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -3 0 0 0 0 0 -3 0 2]
[0 0 -3 0 0 0 0 3 3 -1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[1 1 1 0 0 0 0 0 0 -1]
[0 -3 0 0 0 0 0 -3 0 2]
[0 0 -3 0 0 0 0 3 3 -1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1

8×10 Array{Int64,2}:
 3   3   0  0  0  0  0   3   3  -4
 0  -3   0  0  0  0  0  -3   0   2
 0   0  -3  0  0  0  0   3   3  -1
 0   0   0  3  0  0  0  -3  -6   2
 0   0   0  0  3  0  0   0   0  -1
 0   0   0  0  0  3  0   3   6  -4
 0   0   0  0  0  0  1   1   1  -1
 0   0   0  0  0  0  0   0   0   0

Para hacer ceros sobre el pivote en (2,2):
* sumamos el segundo renglón al primero: $$r^t_1\leftarrow r^t_1+r^t_2$$

$$B\rightarrow\left[\begin{array}{c|c|ccccc|ccc}
 3&   3&   0&  0&  0&  0&  0&   3&   3&  -4\\
 0&  -3&   0&  0&  0&  0&  0&  -3&   0&   2\\
 0&   0&  -3&  0&  0&  0&  0&   3&   3&  -1\\
 0&   0&   0&  3&  0&  0&  0&  -3&  -6&   2\\
 0&   0&   0&  0&  3&  0&  0&   0&   0&  -1\\
 0&   0&   0&  0&  0&  3&  0&   3&   6&  -4\\
 0&   0&   0&  0&  0&  0&  1&   1&   1&  -1\\ \hline
 0&   0&   0&  0&  0&  0&  0&   0&   0&   0
\end{array}\right]$$

In [26]:
C=opera(C)

La matriz actual es:
[3 3 0 0 0 0 0 3 3 -4]
[0 -3 0 0 0 0 0 -3 0 2]
[0 0 -3 0 0 0 0 3 3 -1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Qué tipo de operación desea realizar?
1.-Permutación
2.-Operaciones con renglones
3.-Salir
stdin> 2
Introduzca el índice del renglón que contiene al pivote
stdin> 2
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
Introduzca el índice del renglón a sustituir
stdin> 1
Introduzca el coeficiente entero que multiplica a este renglón
stdin> 1
La matriz resultante es:
[3 0 0 0 0 0 0 0 3 -2]
[0 -3 0 0 0 0 0 -3 0 2]
[0 0 -3 0 0 0 0 3 3 -1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 1 -1]
[0 0 0 0 0 0 0 0 0 0]
¿Desea guardar cambios? (y/n)
stdin> y
La matriz actual es:
[3 0 0 0 0 0 0 0 3 -2]
[0 -3 0 0 0 0 0 -3 0 2]
[0 0 -3 0 0 0 0 3 3 -1]
[0 0 0 3 0 0 0 -3 -6 2]
[0 0 0 0 3 0 0 0 0 -1]
[0 0 0 0 0 3 0 3 6 -4]
[0 0 0 0 0 0 1 1 

8×10 Array{Int64,2}:
 3   0   0  0  0  0  0   0   3  -2
 0  -3   0  0  0  0  0  -3   0   2
 0   0  -3  0  0  0  0   3   3  -1
 0   0   0  3  0  0  0  -3  -6   2
 0   0   0  0  3  0  0   0   0  -1
 0   0   0  0  0  3  0   3   6  -4
 0   0   0  0  0  0  1   1   1  -1
 0   0   0  0  0  0  0   0   0   0

Entonces $B$ es equivalente a la matriz $$C=\left[\begin{array}{ccccccc|ccc}
 3&  0&  0&  0&  0&  0&  0&   0&   3&  -2\\
 0&  -3&  0&  0&  0&  0&  0&  -3&   0&  2\\
 0&  0&  -3&  0&  0&  0&  0&  3&  3&   -1\\
 0&  0&  0&  3&  0&  0&  0&  -3&  -6&   2\\
 0&  0&  0&  0&  3&  0&  0&   0&   0&  -1\\
 0&  0&  0&  0&  0&  3&  0&   3&   6&  -4\\
 0&  0&  0&  0&  0&  0&  1&   1&   1&  -1\\ \hline
 0&  0&  0&  0&  0&  0&  0&   0&   0&   0 \end{array}\right] \rightarrow
 \left[\begin{array}{ccccccc|ccc}
 1&  0&  0&  0&  0&  0&  0&   0&   1&  -2/3\\
 0&  1&  0&  0&  0&  0&  0&  1&   0&  -2/3\\
 0&  0&  1&  0&  0&  0&  0&  -1&  -1&   1/3\\
 0&  0&  0&  1&  0&  0&  0&  -1&  -2&   2/3\\
 0&  0&  0&  0&  1&  0&  0&   0&   0&  -1/3\\
 0&  0&  0&  0&  0&  1&  0&   1&   2&  -4/3\\
 0&  0&  0&  0&  0&  0&  1&   1&   1&  -1\\ \hline
 0&  0&  0&  0&  0&  0&  0&   0&   0&   0 \end{array}\right]$$

En esta matriz es fácil notar la dependencia de las últimas 3 columnas en términos de las primeras 7.

>Entonces la matriz $B$ conserva esta misma dependecia, por lo que: 

$$B=\left[\begin{array}{c|c|c|c|c|c|c|c|c|c}  b_1&b_2&b_3& b_4&b_5&b_6&b_7 & b_8&b_9&b_{10}\end{array}\right]$$
$$B=\left[\begin{array}{c|c|c|c|c|c|c|c|c|c} b_1  & \ldots  & b_7 & b_2-b_3-b_4+b_6 + b_7 & b_1-b_3-2b_4+2b_6+ b_7 & -\frac{2}{3}b_1-\frac{2}{3}b_2+\frac{1}{3}b_3+\frac{2}{3}b_4-\frac{1}{3}b_5-\frac{4}{3}b_6-b_7\end{array} \right]$$

Por lo que una base del núcleo de $B$ está dada por los vectores:
$$\alpha_1=\begin{pmatrix}\ \  0 \ \\-1 \ \\ \ \   1\ \\ \ \  1 \ \\ \ \ 0 \ \\-1 \ \\-1 \ \\ \ \   1 \ \\ \ \   0\  \\ \ \ 0\  \end{pmatrix}; \ \ \ \ \alpha_2=\begin{pmatrix}  -1 \ \\ \ \ 0 \ \\ \ \   1\ \\ \ \  2 \ \\ \ \ 0 \ \\-2 \ \\-1 \ \\ \ \   0 \ \\ \ \   1\  \\ \ \ 0\  \end{pmatrix}; \ \ \ \ \alpha_3=\begin{pmatrix}\ \   \frac{2}{3} \ \\ \ \   \frac{2}{3} \ \\ -   \frac{1}{3} \ \\ -  \frac{2}{3} \ \\ \ \   \frac{1}{3} \ \\ \ \   \frac{4}{3} \ \\  \ \ 1  \ \\ \ \   0 \ \\ \ \   0\  \\ \ \ 1\  \end{pmatrix}$$

Cada uno de los vectores anteriores,contiene los elementos de una matriz mágica:

de $\alpha_1$ recuperamos: $$Q_1=\begin{array}{|c|c|c|}\hline  \ \ 0 \ & -1 \ & \ \ 1\ \\  \hline \ \ 1 \ &\ \  0\ & -1 \ \\ \hline -1\ & \ \ 1 \ & \ \ 0 \ \\ \hline \end{array}$$
de $\alpha_2$ recuperamos: $$Q_2=\begin{array}{|c|c|c|}\hline  -1 \ & \ \ 0 \ & \ \ 1\ \\  \hline \ \ 2 \ &\ \  0\ & -2 \ \\ \hline -1\ & \ \ 0 \ & \ \ 1 \ \\ \hline \end{array}$$
de $\alpha_3$ recuperamos: $$Q_3=\begin{array}{|c|c|c|}\hline   \ \   \frac{2}{3}s \ & \ \   \frac{2}{3}s \ & -   \frac{1}{3}s \ \\ \hline -  \frac{2}{3}s \ & \ \   \frac{1}{3}s \ & \ \   \frac{4}{3}s \ \\  \hline \ \ s  \ & \ \   0 \ & \ \   0\ \\ \hline \end{array}=\frac{s}{3}\begin{array}{|c|c|c|}\hline   \ \   2 \ & \ \   2 \ & -   1\ \\ \hline -  2 \ & \ \   1 \ & \ \   4 \ \\  \hline \ \ 3  \ & \ \   0 \ & \ \   0\ \\ \hline \end{array}$$

Luego todos los cuadrados mágicos de suma $s$ se pueden expresar de la forma: $Q_s=\lambda_1Q_1+\lambda_2Q_2+ Q_3$: $$Q_s=\lambda_1\begin{array}{|c|c|c|}\hline  \ \ 0 \ & -1 \ & \ \ 1\ \\  \hline \ \ 1 \ &\ \  0\ & -1 \ \\ \hline -1\ & \ \ 1 \ & \ \ 0 \ \\ \hline \end{array}+\lambda_2\begin{array}{|c|c|c|}\hline  -1 \ & \ \ 0 \ & \ \ 1\ \\  \hline \ \ 2 \ &\ \  0\ & -2 \ \\ \hline -1\ & \ \ 0 \ & \ \ 1 \ \\ \hline \end{array}+ \frac{s}{3}\begin{array}{|c|c|c|}\hline   \ \   2 \ & \ \   2 \ & -   1\ \\ \hline -  2 \ & \ \   1 \ & \ \   4 \ \\  \hline \ \ 3  \ & \ \   0 \ & \ \   0\ \\ \hline \end{array}; \ \  \ \ \lambda_1,\lambda_2\in \mathbb{R}$$