In [115]:
using LinearAlgebra

In [116]:
A=[1 2 3 4 5 6 7; 2 1 0 0 0 0 0;3 0 1 0 0 0 0; 4 0 0 1 0 0 0; 5 0 0 0 1 0 0; 6 0 0 0 0 1 0; 7 0 0 0 0 0 1]

7×7 Array{Int64,2}:
 1  2  3  4  5  6  7
 2  1  0  0  0  0  0
 3  0  1  0  0  0  0
 4  0  0  1  0  0  0
 5  0  0  0  1  0  0
 6  0  0  0  0  1  0
 7  0  0  0  0  0  1

In [117]:
P=zeros(7,7)+I

7×7 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [118]:
P1=copy(P)

7×7 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [119]:
i=[7,2,3,4,5,6,1]

7-element Array{Int64,1}:
 7
 2
 3
 4
 5
 6
 1

In [120]:
P1=P1[i,:]

7×7 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0

In [121]:
P1*A

7×7 Array{Float64,2}:
 7.0  0.0  0.0  0.0  0.0  0.0  1.0
 2.0  1.0  0.0  0.0  0.0  0.0  0.0
 3.0  0.0  1.0  0.0  0.0  0.0  0.0
 4.0  0.0  0.0  1.0  0.0  0.0  0.0
 5.0  0.0  0.0  0.0  1.0  0.0  0.0
 6.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0

In [122]:
M1=copy(P)

7×7 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [123]:
(1+5)*1//1

6//1

In [124]:
(P1*A)[2:7,1]

6-element Array{Float64,1}:
 2.0
 3.0
 4.0
 5.0
 6.0
 1.0

In [125]:
M1[2:7,1]=-(1//1)*(P1*A)[2:7,1] / (P1*A)[1,1]


6-element Array{Float64,1}:
 -0.2857142857142857 
 -0.42857142857142855
 -0.5714285714285714 
 -0.7142857142857143 
 -0.8571428571428571 
 -0.14285714285714285

In [126]:
M1*P1*A

7×7 Array{Float64,2}:
 7.0  0.0  0.0  0.0  0.0  0.0   1.0     
 0.0  1.0  0.0  0.0  0.0  0.0  -0.285714
 0.0  0.0  1.0  0.0  0.0  0.0  -0.428571
 0.0  0.0  0.0  1.0  0.0  0.0  -0.571429
 0.0  0.0  0.0  0.0  1.0  0.0  -0.714286
 0.0  0.0  0.0  0.0  0.0  1.0  -0.857143
 0.0  2.0  3.0  4.0  5.0  6.0   6.85714 

In [127]:
M2=copy(P)

7×7 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [128]:
(M1*P1*A)[3:7,2]

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 2.0

In [129]:
M2[3:7,2]=-(M1*P1*A)[3:7,2] / (M1*P1*A)[2,2]
M2

7×7 Array{Float64,2}:
 1.0   0.0  0.0  0.0  0.0  0.0  0.0
 0.0   1.0  0.0  0.0  0.0  0.0  0.0
 0.0  -0.0  1.0  0.0  0.0  0.0  0.0
 0.0  -0.0  0.0  1.0  0.0  0.0  0.0
 0.0  -0.0  0.0  0.0  1.0  0.0  0.0
 0.0  -0.0  0.0  0.0  0.0  1.0  0.0
 0.0  -2.0  0.0  0.0  0.0  0.0  1.0

In [130]:
M2*M1*P1*A

7×7 Array{Float64,2}:
 7.0  0.0  0.0  0.0  0.0  0.0   1.0     
 0.0  1.0  0.0  0.0  0.0  0.0  -0.285714
 0.0  0.0  1.0  0.0  0.0  0.0  -0.428571
 0.0  0.0  0.0  1.0  0.0  0.0  -0.571429
 0.0  0.0  0.0  0.0  1.0  0.0  -0.714286
 0.0  0.0  0.0  0.0  0.0  1.0  -0.857143
 0.0  0.0  3.0  4.0  5.0  6.0   7.42857 

In [131]:
M3=copy(P)
M3[4:7,3]=-(M2*M1*P1*A)[4:7,3] / (M2*M1*P1*A)[3,3]
M3*M2*M1*P1*A

7×7 Array{Float64,2}:
 7.0  0.0  0.0  0.0  0.0  0.0   1.0     
 0.0  1.0  0.0  0.0  0.0  0.0  -0.285714
 0.0  0.0  1.0  0.0  0.0  0.0  -0.428571
 0.0  0.0  0.0  1.0  0.0  0.0  -0.571429
 0.0  0.0  0.0  0.0  1.0  0.0  -0.714286
 0.0  0.0  0.0  0.0  0.0  1.0  -0.857143
 0.0  0.0  0.0  4.0  5.0  6.0   8.71429 

In [132]:
M4=copy(P)
M4[5:7,4]=-(M3*M2*M1*P1*A)[5:7,4] / (M3*M2*M1*P1*A)[4,4]
M4*M3*M2*M1*P1*A

7×7 Array{Float64,2}:
  7.0          0.0  0.0  0.0  0.0  0.0   1.0     
  0.0          1.0  0.0  0.0  0.0  0.0  -0.285714
  0.0          0.0  1.0  0.0  0.0  0.0  -0.428571
  0.0          0.0  0.0  1.0  0.0  0.0  -0.571429
  0.0          0.0  0.0  0.0  1.0  0.0  -0.714286
  0.0          0.0  0.0  0.0  0.0  1.0  -0.857143
 -3.55271e-15  0.0  0.0  0.0  5.0  6.0  11.0     

In [133]:
M5=copy(P)
M5[6:7,5]=-(M4*M3*M2*M1*P1*A)[6:7,5] / (M4*M3*M2*M1*P1*A)[5,5]
M5*M4*M3*M2*M1*P1*A

7×7 Array{Float64,2}:
  7.0          0.0  0.0  0.0  0.0  0.0   1.0     
  0.0          1.0  0.0  0.0  0.0  0.0  -0.285714
  0.0          0.0  1.0  0.0  0.0  0.0  -0.428571
  0.0          0.0  0.0  1.0  0.0  0.0  -0.571429
  0.0          0.0  0.0  0.0  1.0  0.0  -0.714286
  0.0          0.0  0.0  0.0  0.0  1.0  -0.857143
 -7.10543e-15  0.0  0.0  0.0  0.0  6.0  14.5714  

In [134]:
M6=copy(P)
M6[7:7,6]=-(M5*M4*M3*M2*M1*P1*A)[7:7,6] / (M5*M4*M3*M2*M1*P1*A)[6,6]
M6*M5*M4*M3*M2*M1*P1*A

7×7 Array{Float64,2}:
 7.0  0.0  0.0  0.0  0.0  0.0   1.0     
 0.0  1.0  0.0  0.0  0.0  0.0  -0.285714
 0.0  0.0  1.0  0.0  0.0  0.0  -0.428571
 0.0  0.0  0.0  1.0  0.0  0.0  -0.571429
 0.0  0.0  0.0  0.0  1.0  0.0  -0.714286
 0.0  0.0  0.0  0.0  0.0  1.0  -0.857143
 0.0  0.0  0.0  0.0  0.0  0.0  19.7143  

In [135]:
M7=copy(P)
M7[1:6,7]=-(M6*M5*M4*M3*M2*M1*P1*A)[1:6,7] / (M6*M5*M4*M3*M2*M1*P1*A)[7,7]
C

UndefVarError: UndefVarError: C not defined

In [136]:
M8=copy(P)
M8[1,1]=1/(M7*M6*M5*M4*M3*M2*M1*P1*A)[1,1]
M8[7,7]=1/(M7*M6*M5*M4*M3*M2*M1*P1*A)[7,7]
M8

7×7 Array{Float64,2}:
 0.142857  0.0  0.0  0.0  0.0  0.0  0.0      
 0.0       1.0  0.0  0.0  0.0  0.0  0.0      
 0.0       0.0  1.0  0.0  0.0  0.0  0.0      
 0.0       0.0  0.0  1.0  0.0  0.0  0.0      
 0.0       0.0  0.0  0.0  1.0  0.0  0.0      
 0.0       0.0  0.0  0.0  0.0  1.0  0.0      
 0.0       0.0  0.0  0.0  0.0  0.0  0.0507246

In [137]:
M8*M7*M6*M5*M4*M3*M2*M1*P1*A

7×7 Array{Float64,2}:
  1.0          0.0  0.0  0.0  0.0  0.0   2.08167e-17
 -1.11022e-16  1.0  0.0  0.0  0.0  0.0  -4.16334e-17
 -4.44089e-16  0.0  1.0  0.0  0.0  0.0  -5.55112e-17
  2.22045e-16  0.0  0.0  1.0  0.0  0.0  -2.77556e-17
  2.22045e-16  0.0  0.0  0.0  1.0  0.0   5.55112e-17
  4.44089e-16  0.0  0.0  0.0  0.0  1.0   5.55112e-17
  0.0          0.0  0.0  0.0  0.0  0.0   1.0        

In [138]:
B=M8*M7*M6*M5*M4*M3*M2*M1*P1

7×7 Array{Float64,2}:
 -0.00724638   0.0144928   0.0217391  …   0.0362319   0.0434783   0.0507246
  0.0144928    0.971014   -0.0434783     -0.0724638  -0.0869565  -0.101449 
  0.0217391   -0.0434783   0.934783      -0.108696   -0.130435   -0.152174 
  0.0289855   -0.057971   -0.0869565     -0.144928   -0.173913   -0.202899 
  0.0362319   -0.0724638  -0.108696       0.818841   -0.217391   -0.253623 
  0.0434783   -0.0869565  -0.130435   …  -0.217391    0.73913    -0.304348 
  0.0507246   -0.101449   -0.152174      -0.253623   -0.304348    0.644928 

In [139]:
B*A

7×7 Array{Float64,2}:
  1.0          0.0  0.0  0.0  0.0  0.0   2.08167e-17
 -1.11022e-16  1.0  0.0  0.0  0.0  0.0  -4.16334e-17
 -4.44089e-16  0.0  1.0  0.0  0.0  0.0  -5.55112e-17
  2.22045e-16  0.0  0.0  1.0  0.0  0.0  -2.77556e-17
  2.22045e-16  0.0  0.0  0.0  1.0  0.0   5.55112e-17
  4.44089e-16  0.0  0.0  0.0  0.0  1.0   5.55112e-17
  0.0          0.0  0.0  0.0  0.0  0.0   1.0        

In [140]:
b=[1 -1 1 -1 1 -1 1]' 

7×1 Adjoint{Int64,Array{Int64,2}}:
  1
 -1
  1
 -1
  1
 -1
  1

In [141]:
x=B*b

7×1 Array{Float64,2}:
  0.014492753623188422
 -1.028985507246377   
  0.9565217391304346  
 -1.0579710144927539  
  0.9275362318840579  
 -1.0869565217391304  
  0.898550724637681   

In [142]:
A*x

7×1 Array{Float64,2}:
  0.9999999999999973
 -1.0               
  0.9999999999999999
 -1.0000000000000002
  1.0               
 -0.9999999999999999
  1.0               

In [143]:
AA=[1 2 3 4 5 6 7 1; 2 1 0 0 0 0 0 -1;3 0 1 0 0 0 0 1; 4 0 0 1 0 0 0 -1; 5 0 0 0 1 0 0 1; 6 0 0 0 0 1 0 -1; 7 0 0 0 0 0 1 1]

7×8 Array{Int64,2}:
 1  2  3  4  5  6  7   1
 2  1  0  0  0  0  0  -1
 3  0  1  0  0  0  0   1
 4  0  0  1  0  0  0  -1
 5  0  0  0  1  0  0   1
 6  0  0  0  0  1  0  -1
 7  0  0  0  0  0  1   1

In [144]:
M8*M7*M6*M5*M4*M3*M2*M1*P1*AA

7×8 Array{Float64,2}:
  1.0          0.0  0.0  0.0  0.0  0.0   2.08167e-17   0.0144928
 -1.11022e-16  1.0  0.0  0.0  0.0  0.0  -4.16334e-17  -1.02899  
 -4.44089e-16  0.0  1.0  0.0  0.0  0.0  -5.55112e-17   0.956522 
  2.22045e-16  0.0  0.0  1.0  0.0  0.0  -2.77556e-17  -1.05797  
  2.22045e-16  0.0  0.0  0.0  1.0  0.0   5.55112e-17   0.927536 
  4.44089e-16  0.0  0.0  0.0  0.0  1.0   5.55112e-17  -1.08696  
  0.0          0.0  0.0  0.0  0.0  0.0   1.0           0.898551 